version: '3.9'

services:
  postgres:
    image: postgres
    container_name: app_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_app
    ports:
      - "5435:5432"
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data: